-- USUARIO ADMIN
CREATE USER 'admin' @'%' IDENTIFIED WITH caching_sha2_password BY 'admin'
GRANT USAGE ON *.* TO 'admin' @'%';
ALTER USER 'admin' @'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT,
    INSERT,
    UPDATE ON `cassandravideo`.* TO 'admin' @'%';
ALTER USER 'admin' @'%';
-- USUARIO GUESS
CREATE USER 'guess' @'%' IDENTIFIED WITH caching_sha2_password BY 'guess';
GRANT USAGE ON *.* TO 'guess' @'%';
ALTER USER 'guess' @'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT ON `cassandravideo`.* TO 'guess'@'%'; ALTER USER 'guess'@'%' ;